const cardImages: { [key: string]: any } = {
  "1.png": require("../../assets/cards/1.png"),
  "2.png": require("../../assets/cards/2.png"),
  "3.png": require("../../assets/cards/3.png"),
  "4.png": require("../../assets/cards/4.png"),
  "5.png": require("../../assets/cards/5.png"),
  "6.png": require("../../assets/cards/6.png"),
  "7.png": require("../../assets/cards/7.png"),
  "8.png": require("../../assets/cards/8.png"),
  "9.png": require("../../assets/cards/9.png"),
  "10.png": require("../../assets/cards/10.png"),
  "11.png": require("../../assets/cards/11.png"),
  "12.png": require("../../assets/cards/12.png"),
  "13.png": require("../../assets/cards/13.png"),
  "14.png": require("../../assets/cards/14.png"),
  "15.png": require("../../assets/cards/15.png"),
  "16.png": require("../../assets/cards/16.png"),
  "17.png": require("../../assets/cards/17.png"),
  "18.png": require("../../assets/cards/18.png"),
  "19.png": require("../../assets/cards/19.png"),
  "20.png": require("../../assets/cards/20.png"),
  "21.png": require("../../assets/cards/21.png"),
  "22.png": require("../../assets/cards/22.png"),
  "23.png": require("../../assets/cards/23.png"),
  "24.png": require("../../assets/cards/24.png"),
  "25.png": require("../../assets/cards/25.png"),
  "26.png": require("../../assets/cards/26.png"),
  "27.png": require("../../assets/cards/27.png"),
  "28.png": require("../../assets/cards/28.png"),
  "29.png": require("../../assets/cards/29.png"),
  "30.png": require("../../assets/cards/30.png"),
  "31.png": require("../../assets/cards/31.png"),
  "32.png": require("../../assets/cards/32.png"),
  "33.png": require("../../assets/cards/33.png"),
  "34.png": require("../../assets/cards/34.png"),
  "35.png": require("../../assets/cards/35.png"),
};

export default cardImages;